#!/bin/bash

read -p "Name: " name
read -p "Password: " -s pass
echo
curl --cookie ~/.config/suckless/surf/cookies.txt --cookie-jar ~/.config/suckless/surf/cookies.txt \
-d "session[username_or_email]=$name" \
-d "session[password]=$pass" \
-d "remember_me=1" \
-d "commit=Sign In" \
http://twitter.com/sessions > /dev/null
curl --cookie ~/.config/suckless/surf/cookies.txt --cookie-jar ~/.config/suckless/surf/cookies.txt \
http://twitter.com/ > /dev/null
surf http://mobile.twitter.com
