#!/bin/sh


#unicode icons 🔆 🔅 🌣

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
cur_bright=$(cat /sys/class/backlight/intel_backlight/brightness)
max_bright=$(cat /sys/class/backlight/intel_backlight/max_brightness)

#math to convert into percentages
perc_bright="$(($cur_bright * 100 / $max_bright))"

if [ "$cur_bright" -lt 10 ]; then
  perc_bright=1;
fi


case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e light & ;;
	3) light -A 1 >/dev/null 2>/dev/null ;;
	4) light -U 1 >/dev/null 2>/dev/null ;;
	2) pgrep -x dunst >/dev/null && notify-send " Shows brightness 🔆.";;
esac

icon="🔆"
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

printf " %s%s%% \\n" "$icon""$perc_bright"